# 站点名称
site_name: 'ToolGuide'
# 仓库链接
repo_url: https://github.com/ZJDoc/ToolGuide
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2021, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
  # 参考[MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)，支持数学公式渲染
  - pymdownx.arithmatex:
      generic: true
    # 参考[Icons + Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)，执行Markdown Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# mathjax
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 导航
nav:
    - Home: index.md
    - 建模:
      - UML:
        - 统一建模语言UML: uml/统一建模语言UML.md
        - '[译][wiki]Class-Diagram': uml/Class-Diagram.md
        - 类图小结: uml/类图小结.md
      - PlantUML:
        - 'PlantUML简介': './uml/plantuml/PlantUML简介.md'
        - '本地安装和使用': './uml/plantuml/本地安装和使用.md'
        - 'VSCode插件使用': './uml/plantuml/VSCode插件使用.md'
        - '常用命令': './uml/plantuml/常用命令.md'
        - '类图使用': './uml/plantuml/类图使用.md'
    - 工具:
      - JetBrains:
        - '安装': './jetbrains/安装.md'
        - '学生认证': './jetbrains/学生认证.md'
        - '文件模板': './jetbrains/文件模板.md'
        - CLion:
          - 'OpenCV配置': './jetbrains/clion-OpenCV配置.md'
          - 'could not load cache': './jetbrains/clion-Error: could not load cache.md'
        - PyCharm:
          - '[PyCharm]pytest设置和使用': './jetbrains/pycharm-pytest设置和使用.md'    
      - Jupyter:
        - '[conda]JupyterLab安装': './jupyter/[conda]JupyterLab安装.md'
        - '远程访问配置': './jupyter/远程访问配置.md'
        - '基本功能介绍': './jupyter/基本功能介绍.md'
        - '[PEP8]代码格式化': './jupyter/[PEP8]代码格式化.md'
        - '目录生成插件': './jupyter/目录生成插件.md'
      - VSCode: 
        - Home: './vscode/index.md'
        - 系统:
          - '引言': './vscode/system/引言.md'
          - '安装': './vscode/system/安装.md'
          - '布局': './vscode/system/布局.md'
          - '用户和工作空间设置': './vscode/system/用户和工作空间设置.md'
          - '快捷键设置': './vscode/system/快捷键设置.md'
          - '命令行操作': './vscode/system/命令行操作.md'
          - '代码片段': './vscode/system/代码片段.md'
          - 'tab键失效': './vscode/system/tab键失效.md'
        - 语言:
          - 'C++环境配置': './vscode/languages/C++环境配置.md'
          - 'Python环境配置': './vscode/languages/Python环境配置.md'
          - '[OpenCV 3.4.2]pylint检测错误': './vscode/languages/[OpenCV 3.4.2]pylint检测错误.md'
        - 插件:
          - 'Git设置': './vscode/extensions/git设置.md'
          - '[SSH]远程服务配置': './vscode/extensions/[SSH]远程服务配置.md'
          - '[GitLens]无法打开': './vscode/extensions/gitlens-无法打开.md'
        - 自定义:
          - 显示隐藏文件: vscode/custom/显示隐藏文件.md
    - 环境:
      - Anaconda:
        - '环境查询，安装，卸载，克隆': './anaconda/环境查询，安装，卸载，克隆.md'
        - 卸载包: anaconda/卸载包.md
        - '查询、安装指定版本': './anaconda/查询、安装指定版本.md'
        - 配置国内镜像源: anaconda/配置国内镜像源.md
        - conda安装环境报错: anaconda/conda安装环境报错.md
        - '[conda clean]环境清理': './anaconda/[conda clean]环境清理.md'
        - Miniconda: anaconda/Miniconda.md
        - 环境迁移: anaconda/环境迁移.md
      - NodeJS:
        - nodeJS安装: node/nodeJS安装.md
        - nodeJS初始化: node/nodeJS初始化.md
        - npm和cnpm: node/npm和cnpm.md
        - '[npm]查询': './node/[npm]查询.md'
        - '[npm]安装': './node/[npm]安装.md'
        - '[npm]卸载': './node/[npm]卸载.md'
        - '[package.json]脚本运行': './node/[package.json]脚本运行.md'
        - '[pkg]打包可执行文件': './node/[pkg]打包可执行文件.md'
      - NDK:
        - NDK开发概述: android/ndk/NDK开发概述.md
        - 'ndk-build编译失败': android/ndk/ndk-build编译失败.md
        - '[Ubuntu]android studio配置javah和ndk-build': './android/ndk/[Ubuntu]android studio配置javah和ndk-build.md'
        - '[Ubuntu]NDK配置OpenCV': './android/ndk/[Ubuntu]NDK配置OpenCV.md'
        - 'libopencv_java3.so not found': './android/ndk/libopencv_java3.so not found.md'